# SPDX-FileCopyrightText: 2015 Angelo Veltens <angelo.veltens@online.de>
#
# SPDX-License-Identifier: MIT

version: 2
updates:
- package-ecosystem: docker
  directory: /src
  schedule:
    interval: daily
    time: 04:00
  open-pull-requests-limit: 10
