# SPDX-FileCopyrightText: 2015 Angelo Veltens <angelo.veltens@online.de>
#
# SPDX-License-Identifier: MIT

# Here are some commonly used pre-commit hooks. You can find more at:
# <https://github.com/pre-commit/pre-commit-hooks>
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
  - id: shellcheck
    args: [--external-sources, --shell=bash, --severity=warning]
    files: \.(ba)?sh$
- repo: https://github.com/fsfe/reuse-tool
  rev: v3.1.0a1
  hooks:
  - id: reuse
    name: Check license headers (REUSE)
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.7.3
  hooks:
  - id: editorconfig-checker
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint
    name: Fixing markdown linting errors
    args: [--disable, MD013, MD033, --fix]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
